version: 2.1

commands:
  print_pipeline_id:
    description: "print pipeline id"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID
jobs:
  print_workflow_id:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - print_pipeline_id
workflows:
  print-workflow:
    jobs:
      - print_workflow_id
