version: 2.1

commands:
  print_pipeline_id:
    description: "print pipeline id"
    parameters:
      id:
        type: string
    steps:
      - run: echo << parameters.id >>
jobs:
  print_workflow_id:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>
workflows:
  print-workflow:
    jobs:
      - print_workflow_id
